# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
use Mix.Config

config :string_naming, categories:
  ~w|
      =AManAndHisOccupations
      =ATheHumanBodyAndClothing
      #AaUnclassified
      #AbbreviationMark
      #AbbreviationSign
      #AbbreviationsInvolvingLiterSymbols
      #AbkhazLetters
      #AccentMarks
      =Accidental
      =Accidentals
      =AccommodationSymbol
      =AccommodationSymbols
      #AdditionForGermanTypography
      #AdditionForKashmiri
      #AdditionForSanskrit
      #AdditionForTorwali
      #AdditionForUpa
      #AdditionalArchaicLettersForBactrian
      #AdditionalBoldGreekSymbols
      #AdditionalBoldItalicGreekSymbols
      #AdditionalCircledNumber
      #AdditionalConsonant
      #AdditionalConsonants
      #AdditionalDependentVowelSigns
      #AdditionalDiacriticalMarkForSymbols
      #AdditionalDiacriticalMarksForSymbols
      #AdditionalEnclosingDiacritics
      #AdditionalHistoricVowel
      #AdditionalItalicGreekSymbols
      #AdditionalLetter
      #AdditionalLetterForOssetian
      #AdditionalLetterlikeSymbols
      #AdditionalLetters
      #AdditionalLettersForMingrelianAndSvan
      #AdditionalLettersForOssetianAndAbkhaz
      #AdditionalMarksForUpa
      #AdditionalNasalVowels
      #AdditionalPunctuation
      #AdditionalSansSerifBoldGreekSymbols
      #AdditionalSansSerifBoldItalicGreekSymbols
      #AdditionalSigns
      #AdditionalSuzhouNumerals
      #AdditionalVowelsForSanskrit
      #AdditionalWhiteOnBlackCircledNumber
      #Additions
      #AdditionsBasedOn1989Ipa
      #AdditionsForAfricanistLinguistics
      #AdditionsForAssamese
      #AdditionsForBurushaski
      #AdditionsForEarlyPersian
      #AdditionsForEarlyPersianAndAzerbaijani
      #AdditionsForExtendedIpa
      #AdditionsForGreek
      #AdditionsForIpa
      #AdditionsForKhowar
      #AdditionsForLithuanianDialectology
      #AdditionsForLivonian
      #AdditionsForNivkh
      #AdditionsForRomanian
      #AdditionsForSencoten
      #AdditionsForShanPali
      #AdditionsForShona
      #AdditionsForSinology
      #AdditionsForSlovenianAndCroatian
      #AdditionsForTheUralicPhoneticAlphabet
      #AdditionsForUighur
      #AdditionsForUpa
      #AfonaOrYpostaseisMutesOrHypostases
      #AfricanLettersForClicks
      #AfricanistToneLetters
      #AgogikaConduits
      #AitonSymbolsAndLetters
      #AleutLetters
      #AlloioseisDifferentiators
      #AlternateConsonantFormsForChinese
      #AlternateFormsOfPunctuation
      #AlternateLetters
      #AlternateVowelSigns
      #AmpersandAndLigatureEtOrnaments
      =Analytics
      #AncientGreekAcrophonicNumerals
      #AncientGreekInstrumentalNotation
      #AncientGreekPapyrologicalNumbers
      #AncientGreekSymbols
      #AncientGreekTextualSymbols
      #AncientGreekVocalicNotation
      #AncientNearEasternLinguisticSymbol
      #AncientRomanEpigraphicLetters
      =Angles
      AnimalFaces
      AnimalSymbols
      #AnnotationMarks
      #Anusvaras
      #Apl
      #Apparatus
      #ArabicIndicDigits
      #ArabicLetterForBerber
      #ArabicLettersForAfricanLanguages
      #ArabicLettersForArwi
      #ArabicLettersForBravanese
      #ArabicLettersForEuropeanAndCentralAsianLanguages
      #ArabicLettersForWarshOrthography
      #ArabicPedagogicalSymbols
      #ArcConsonants
      #ArchaicBaselineToneMarks
      #ArchaicLetters
      #ArchaicLettersForEwe
      #ArchaicLettersForVolapK
      #ArchaicLowercaseSyllable
      #ArchaicPunctuation
      #ArchaicRomanNumerals
      #ArchaicUppercaseSyllable
      #Ardhavisarga
      #ArgiesRetards
      #AribCompatibilityIdeographs
      #ArmenianLigatures

      #ArrowTails
      #Arrowheads
      #Arrows
      #ArrowsCombinedWithOperators
      #ArrowsCombinedWithRelations
      #ArrowsWithBentTips
      #ArrowsWithEquilateralTriangleArrowheads
      #ArrowsWithModifications
      #ArrowsWithTriangleArrowheads

      #Articulation
      #AsciiDigits
      #AsciiPunctuationAndSymbols
      =AstrologicalDigits
      =AstrologicalSigns
      =AstrologicalSymbols
      =AstronomicalSymbol
      #AttachedAffixes
      =AudioAndVideoSymbols
      #AugmentationDot
      #AzerbaijaniLetters
      #BAnimals
      #BWomanAndHerOccupations
      =BackOfCard
      =BallotSymbols
      =BambooSuitTiles
      #Bars
      #BasedOnGb2312
      #BasedOnIso88596
      #BasedOnIso88598
      #BaselineToneMarks
      #BasicConsonants
      #BasicGlyphsForArabicLanguageContextualForms
      #BasicLetters
      #BasicNasalVowels
      #BasicRussianAlphabet
      #BasicSyllables
      #BeamsAndSlurs
      =BeverageAndFoodSymbols
      =BeverageSymbols
      =BiblicalEditorialSymbol

      =BlackArrow
      =BlackCircles
      =BlackCurvedArrows
      =BlackDiamonds
      =BlackLozenges
      =BlackSquares

      #BlockElements
      =BodyShapes
      #BohairicCopticLetters

      =BoldDigits
      =BoldFrakturSymbols
      =BoldGreekSymbols
      =BoldItalicGreekSymbols
      =BoldItalicSymbols
      =BoldScriptSymbols
      =BoldSymbols

      =BowtieSymbols

      =BracketPieces
      =Brackets
      =BracketsWithTicks

      BraillePatterns
      #BreathingMarkForTheSamaveda
      =BubbleSymbols
      BuildingAndMapSymbols
      #CAnthropomorphicDeities
      #CPlants
      #Candrabindu
      #CantillationMarks
      #CantillationMarksSvaraForTheSamaveda
      #CantillationSigns
      #CapitalLetters
      #CapitalLettersKhutsuri
      CatFaces
      #CaucasianLinguistics
      #CeilingsAndFloors
      =CelebrationSymbols
      =CentredGeometricShapes
      =CerealsAndPlants
      #CharacterCellArcs
      #CharacterCellDiagonals
      =CharacterSuitTiles
      #CharactersFoundThroughPhaseA
      #CharactersFoundThroughPhaseB
      #CharactersFoundThroughPhaseC
      #CharactersFoundThroughPhaseD
      #CharactersFoundThroughPhaseE
      #CharactersFoundThroughPhaseF
      =ChemistrySymbol
      ChessSymbols
      #ChilluLetters
      #ChinantecToneMarks
      #ChinookPunctuation
      #ChukchiLetters
      #ChuvashLetters

      =Circle
      =CircleSuitTiles
      =CircleSymbols
      =CircleVowels
      =CircledArrows
      #CircledHangulLetters
      #CircledHangulSyllable
      #CircledHangulSyllables
      #CircledIdeographs
      #CircledIdeographsFromAribStdB24
      =CircledItalicLatinLetters
      #CircledKatakana
      #CircledKoreanWords
      CircledLatinLetterSequences
      CircledLatinLetters
      CircledNumbers
      #CircledNumbersOnBlackSquaresFromAribStdB24
      #CircledSansSerifDigits
      #Circles

      #CjkAngleBrackets
      #CjkBrackets
      #CjkCornerBrackets
      #CjkRadicalsSupplement
      #CjkStrokes
      #CjkSymbols
      #CjkSymbolsAndPunctuation
      #ClaudianLetters
      #Clef
      #Clefs
      =ClockFaceSymbols
      ClothingAndAccessories
      =ClubsOrWands
      #Codas
      #CombiningDiacriticalMarks
      #CombiningDiacriticalMarksForSymbols
      #CombiningHalfMarks
      #CombiningHalfMarksBelow
      #CombiningLetters
      #CombiningMaddahAndHamza
      #CombiningMarks
      #CombiningMarksForOldCyrillic
      #CombiningNumberBases
      #CombiningNumericSigns
      #CombiningStroke
      #CombiningToneMarks
      =ComicStyleSymbols
      CommunicationSymbols
      =ComplexSigns
      =ComplexSignsWithVaseShapes
      #CompoundVowels
      =CompressedArrows
      =ComputerSymbols
      #ConjunctionAndLengthMarks
      #Consonant
      #ConsonantAdditionForTibetan
      #ConsonantAdditionsForSanskrit
      #ConsonantForAdduDialect
      #ConsonantLetters
      #ConsonantModifiers
      #ConsonantOnsets
      #ConsonantShifters
      #ConsonantSigns
      #Consonants
      #ConsonantsAndConsonantSigns
      #ConsonantsForKhmu
      #ContactMovementIndicators
      #ContinuousMacronsForCoptic
      #ContourToneMarks
      #ControlCodeGraphics
      #CopticLettersDerivedFromDemotic
      #CornerToneMarksForChinese
      #CountingRodUnits
      #CroatianDigraphsMatchingSerbianCyrillicLetters
      #Crops
      =Crosses
      =CrossingArrowsForKnotTheory
      #CryptogrammicLetters
      #CryptogrammicMark
      CulturalSymbols
      =CurrencySign
      =CurrencySigns
      =CurrencySymbol
      =CurrencySymbols
      #CuspShapes
      #CyrillicExtensions
      #CyrillicLetter
      #DNature
      #DPartsOfTheHumanBody
      =Dash
      =Dashes
      =DatabaseTheoryOperators
      =DateMark
      =DentistryNotationSymbols
      #DependentConsonantSigns
      #DependentConsonantsForRohingya
      #DependentVowelSign
      #DependentVowelSigns
      #DependentVowelSignsForKashmiri
      #DependentVowels
      #Deprecated
      #DeprecatedAngleBrackets
      #DeprecatedIndependentVowelsForTransliteration
      #DeprecatedLetter
      #DiacriticForAmericanLexicography
      #DiacriticalMarks
      #DiacriticalMarksForMusicalSymbols
      #Diacritics
      #DiacriticsForVisarga
      #DiagonalLineVowels
      #DialectNonMandarinLetters
      =Diamonds
      =DiamondsAndLozenges
      =DiamondsOrPentacles
      Dice
      DictionaryAndMapSymbols
      =DictionaryAndMapSymbolsFromAribStdB24
      =DictionaryPunctuation
      =Digits
      =DigitsMinusHalf
      =Digrams
      =Digraphs
      =DingbatArrow
      =DingbatArrows
      DingbatCircledDigits
      #DivisionOperator
      #DotReph
      =DotlessSymbols
      #DottedCircleVowels
      #DottedToneLetters

      =DoubleArrows
      =DoubleBarbedHarpoons
      =DoubleCircledNumbers
      #DoubleDiacritic
      #DoubleDiacriticMarkForUpa
      #DoubleDiacritics
      =DoubleHyphen
      =DoubleLines
      =DoublePunctuationForVerticalText
      =DoubleStruckDigits
      =DoubleStruckItalicMathSymbols
      =DoubleStruckLargeOperator
      =DoubleStruckSymbols

      #DprkCompatibilityIdeographs
      =DraftingSymbols
      =DragonTiles
      #DuplicateCharactersFromBig5
      #DuplicateCharactersFromCns116431992
      #Dynamics
      #DynamicsIndicators
      #EBuildings
      #EMammals
      #EasternArabicIndicDigits
      #EditorialMarks
      =EditorialSymbols
      #EgyptologicalAdditions
      #EightPointedStars
      #EightSpokedAsterisks
      #EightStrokeComponents
      #Ekfonetika
      #ElamiteFractions
      #ElamiteNumericSigns
      #ElamiteSign
      =ElectrotechnicalSymbols
      =ElectrotechnicalSymbolsFromIr181
      #ElevenStrokeComponents
      =Ellipses
      =EllipsisMarks
      EmojiModifiers
      EmoticonFaces
      Emoticons
      =EmptySets
      #EnclosedAlphanumericSymbols
      #EnclosingDiacritics
      EntertainmentSymbols
      =ErrorBarSymbols
      #EuropeanLatin
      #ExtendedArabicLetter
      #ExtendedArabicLetterForParkari
      #ExtendedArabicLetters
      #ExtendedArabicLettersForParkari
      #ExtendedArabicMark
      #ExtendedBopomofoForHmuAndGe
      #ExtendedBopomofoForMinnanAndHakka
      #ExtendedBopomofoToneMarks
      #ExtendedCyrillic
      #ExtendedVowelSignForArwi
      #ExtendedVowelSigns
      #ExtendedVowelSignsForAfricanLanguages
      #ExtendedVowelSignsForRohingya
      #ExtensionForGebaKaren
      #ExtensionsForAitonAndPhake
      #ExtensionsForArabic
      #ExtensionsForBalti
      #ExtensionsForEasternPwoKaren
      #ExtensionsForKayah
      #ExtensionsForKhamtiShan
      #ExtensionsForMon
      #ExtensionsForRumaiPalaung
      #ExtensionsForSGawKaren
      #ExtensionsForSanskritAndTibetan
      #ExtensionsForShan
      #ExtensionsForWesternPwoKaren
      #Extracts
      #FArmsToolsFurnitureAndOtherInstruments
      #FPartsOfMammals
      Faces
      =FacialPartsSymbols
      FairyTaleSymbols
      =Fences
      #FigureRepetitions
      #FillModifiers
      #FinalConsonants
      #FinalLetters
      #FinalsForCreeAndOjibway
      #FinalsForDeneAndCarrier
      #FingerMovementIndicators
      =FingerPostArrows
      =FishTails
      #FivePointedStars
      #FiveSpokedAsterisks
      #FiveStrokeComponents
      #Fives
      #FixedFormSubjoinedConsonants
      #FlagSymbols
      Flags
      =Fleurons
      =FlowerTiles
      #FonitikaVocals
      FoodSymbol
      FoodSymbols
      #ForfedaSupplementaryLetters
      =Forks
      #FormatCharacter
      #FormatCharacters
      #FormatControls
      #FourPointedStars
      #FourStrokeComponents
      #Fours
      =Fraction
      =FractionSigns
      =Fractions
      =FractionsAndCompoundFractions
      FrakturSymbols
      FrownAndSmile
      FruitAndVegetableSymbols
      #FthoresDestroyers
      FullwidthAsciiVariants
      FullwidthBrackets
      FullwidthSymbolVariants
      #FurtherGreekMusicalNotationSymbols
      #GBirds
      #GVasesAndReceptacles
      =GameSymbol
      =GameSymbols
      #GameSymbolsFromAribStdB24
      #GamoGofaDawro
      #GamoGofaDawroAndBasketo
      #GapFillers
      =GenderSymbol
      =GenderSymbols
      =GenealogicalSymbols
      =GeneralPunctuation
      #GenericPunctuationForPhilippineScripts
      #GenericPunctuationForScriptsOfIndia
      =GeometricShapes
      =GeometricSymbols
      =GestureSymbols
      =GlobeSymbols
      #GlottalStop
      #GlyphPart
      #GlyphsForContextualFormsOfLettersForCentralAsianLanguages
      #GlyphsForContextualFormsOfLettersForPersianUrduSindhiEtc
      #GlyphsForSpacingFormsOfArabicPoints
      #GlyphsForVerticalVariants
      GoMarkers
      =GoldenNumberRunes
      #GrammataLetters
      #GraphemeJoiner
      #GraphicPictureForControlCode
      #GraphicPicturesForControlCodes
      #GraphicsForControlCodes
      =GreekCrosses
      =GreekLetters
      =GreekSubscriptModifierLetters
      =GreekSuperscriptModifierLetters
      =GreekSymbol
      #Gumuz
      #GurmukhiSpecificAdditions
      #HPartsOfBirds
      #HSymbols
      =HalfBrackets
      =HalfCircles
      #HalfwidthCjkPunctuation
      #HalfwidthHangulVariants
      #HalfwidthKatakanaVariants
      =HalfwidthSymbolVariants

      =HandShapesWithFiveFingers
      =HandShapesWithFourFingers
      =HandShapesWithIndexAndMiddleFingers
      =HandShapesWithIndexAndMiddleFingersAndThumb
      =HandShapesWithIndexFinger
      =HandShapesWithIndexFingerAndThumb
      =HandShapesWithLittleFinger
      =HandShapesWithMiddleFinger
      =HandShapesWithRingFinger
      =HandShapesWithThumb
      =HandSymbols

      =Harpoons
      =HeadMark
      =HeadMarks
      #HeadMarksForTibetan
      =HeadShapes
      HeartSymbol
      HeartSymbols
      =HeartsOrCups
      =HeavyArrowShafts
      =HeavyArrows
      =HeavyVariantsOfArithmeticSymbols
      #HebrewLetterlikeMathSymbols
      #HebrewPresentationForms
      #Hexagons
      #HighAffixes
      #HiraganaDigraph
      #HiraganaLetters
      #HistoricCurrencySign
      #HistoricDigraphs
      #HistoricHiragana
      #HistoricKatakana
      #HistoricLetterVariants
      #HistoricLetters
      #HistoricLettersForSakhaYakut
      #HistoricMiscellaneous
      #HistoricPhoneticVariants
      #HistoricPunctuation
      #HistoricSyllables
      #HistoricSymbolsForFractionalValues
      #HistoricalDigits
      #HistoricalNumbers
      #HoldsAndPauses
      #Honorifics
      #HoraDigits
      =HorizontalBrackets
      #HorizontalTiles
      #HundredThousands
      #Hundreds
      #IAmphibiousAnimalsReptilesEtc
      #IchimataAndMartyrikaIchimasAndEvidentials
      #IdeographicDescriptionCharacters
      #IdeographsWithTortoiseShellBracketsFromAribStdB24
      #IndependentVowelForMarathi
      #IndependentVowelSigns
      #IndependentVowels
      #IndependentVowelsAndDvisvara
      #IndependentVowelsForKashmiri
      #InherentVowels
      #InitialConsonants
      #InitialSymbols
      #Instrumentation
      #InsularAndCelticistLetters
      =IntegralPieces
      =Integrals
      =InterlinearAnnotation
      =IntersectionsAndUnions
      #IntonationMarksForLithuanianDialectology
      #InvisibleOperators
      #InvocationSigns
      #IotaSubscript
      #IpaCharactersForDisorderedSpeech
      #IpaDiacriticsForDisorderedSpeech
      #IpaExtensions
      #IpaModifiers
      #IsolatedSymbols
      #IsoscelesRightTriangles
      #ItalicGreekSymbols
      #ItalicSymbols
      #IterationMarks
      #JLinesNumbersAndGeometricShapes
      #JapaneseChessSymbols
      #JapaneseCorporation
      #JapaneseEraNames
      #JapaneseSchoolGradeSymbols
      #JisX0213CompatibilityIdeographs
      Joker
      #KFishesAndPartsOfFishes
      #KVaria
      #Kaeriten
      #KangxiRadicals
      #KatakanaDigraph
      #KatakanaLetters
      #KatakanaPunctuation
      =KeyboardAndUiSymbols
      =KeyboardSymbol
      =KeyboardSymbols
      =KeyboardSymbolsAndCircleArrows
      =KeyboardSymbolsFromIso99957
      #KhamtiShanConsonants
      #KhamtiShanLogograms
      #KhantyLetters
      #KomiLetters
      #KoranicAnnotationSign
      #KoranicAnnotationSigns
      #KoreanCompatibilityIdeographs
      #KurdishLetters
      #LInvertabrataAndLesserAnimals
      =LargeOperators
      #Latin1PunctuationAndSymbols
      #LatinExtensionsForVietnamese
      #LatinGeneralExtensions
      #LatinGeneralUseExtensions
      #LatinLetter
      #LatinLetterWithTortoiseShellBrackets
      #LatinLetters
      #LatinLettersWithMiddleTilde
      #LatinLettersWithPalatalHook
      #LatinLettersWithRetroflexHook
      #LatinLigatures
      #LatinSubscriptModifierLetters
      #LatinSuperscriptModifierLetters
      #LatvianLettersForPre1921Orthography
      #LeftStemToneLetters
      #LeimmataOrSiopesLeimmasOrSilencers
      #LengthMark
      #Letter
      #LetterA
      #LetterExtender
      #LetterForAfricanLanguages
      #LetterForGermanDialectology
      #LetterForWestAfricanLanguages
      #LetterlikeSymbol
      #LetterlikeSymbols
      #Letters
      #LettersForAfricanLanguages
      #LettersForAmericanistOrthographies
      #LettersForGermanDialectology
      #LettersForMiddleVietnamese
      #LettersForOldAbkhasianOrthography
      #LettersForOldCyrillic
      #LigaturesThreeElements
      #LigaturesTwoElements
      #LightAndDoubleLineBoxComponents
      #LightAndHeavyDashedLines
      #LightAndHeavyHalfLines
      #LightAndHeavyLineBoxComponents
      #LightAndHeavySolidLines
      #LineConsonants
      #LocationBases
      =LogicalAndSetOperators
      =LogicalAndsAndOrs
      =LogicalOperators
      =Logograms
      =Logographs
      #LogographsForClanNames
      =LongArrows
      #LoopedSymbols
      #LowAffixes
      #LowercaseClaudianLetter
      #LowercaseConsonants
      #LowercaseLatinAlphabet
      #LowercaseLetters
      #LowercaseOfEditorialSymbols
      #LowercaseSyllables
      #LowercaseVowels
      =LunarDateSign
      =LunarDateSymbols
      =MAdditionalSigns
      =MTreesAndPlants
      =MalayalamNumerics
      #ManchuLetters
      MapSymbol
      #MapSymbolFromAribStdB24
      #MapSymbolsFromAribStdB24
      =Marks
      =MarksAndSigns
      =MarksOfNasalization
      #MathematicalArrows
      #MathematicalBrackets
      #MathematicalOperator
      #MathematicalOperators
      #MayanistAdditions
      =MeasurementSymbol
      =Measures
      #MedialVowels
      #Medials
      =MedicalAndHealingSymbols
      MedicalSymbols
      #MedievalSuperscriptLetterDiacritics
      #MedievalistAddition
      #MedievalistAdditions
      #MelodimataMelodics
      #MensuralNotes
      #MensuralProlations
      #MensuralRests
      =Metals
      =MetricalSymbols
      #Micr
      #MinorFractions

      #Miscellaneous
      #MiscellaneousAddition
      #MiscellaneousAdditions
      #MiscellaneousArrow
      #MiscellaneousArrowSymbol
      #MiscellaneousArrows
      #MiscellaneousArrowsAndKeyboardSymbols
      #MiscellaneousCurvedArrows
      #MiscellaneousLargeOperators
      #MiscellaneousMark
      #MiscellaneousMarks
      #MiscellaneousMathematicalOperator
      #MiscellaneousMathematicalOperators
      #MiscellaneousMathematicalSymbol
      #MiscellaneousMathematicalSymbols
      #MiscellaneousPhoneticModifiers
      #MiscellaneousPunctuation
      #MiscellaneousSign
      #MiscellaneousSymbol
      #MiscellaneousSymbolFromAribStdB24
      #MiscellaneousSymbols
      #MiscellaneousTechnical
      #MiscellaneousTiles

      #MixedLightAndHeavyLines
      #Mkhedruli
      #ModalLogicOperators
      #ModifiedHarpoons
      #ModifierLetter
      #ModifierLetters
      #ModifierLettersForGermanDialectology
      #Modifiers
      MoneySymbols
      #Monogram
      MonospaceDigits
      MonospaceSymbols
      =MoonSunAndStarSymbols
      #MordvinLetters
      #MovementIndicators
      =MultiplicationAndDivisionSignOperators
      MusicalSymbols
      MusicalSymbolsForNotes
      #NAryOperators
      #NSkyEarthWater
      #NewTestamentEditorialSymbols
      #NineStrokeComponents
      #NlNomesOfLowerEgypt
      #NonEuropeanAndHistoricLatin
      #NonJoiningConsonants
      #NotchedArrows
      #Noteheads
      #Notes
      #NuNomesOfUpperEgypt
      #Nukta
      #NumberForms
      #NumberJoiner
      #NumberWithFullStop
      #Numbers
      #NumbersPeriod
      #NumbersWithComma
      #NumeralSigns
      #Numerals
      #NumericCharacter
      #NumericSigns
      #NumericSymbolsForDivinationLore
      #OBuildingsPartsOfBuildingsEtc
      #Ocr
      #OcrA
      #Octaves
      OfficeSymbols
      #OldChurchSlavonicCombiningLetters
      #OldConsonantLetters
      #OldCopticAndDialectLetters
      #OldFinalConsonants
      #OldInitialConsonants
      #OldMedialVowels
      #OldNubianLetters
      #OldNubianPunctuation
      #OldVowelLetters
      #OneStrokeComponents
      #Ones
      #Operator
      #Operators
      #OrdinaryDiacritics
      #OrnamentalBrackets
      #Ornamentation
      #Ornaments
      #OrokLetters
      #OrthographicLatinAdditions
      #OrthographicLettersForGlottals
      #OscanLetters
      #OtherCjkPunctuation
      #OtherCjkSymbols
      #OtherCombiningMarks
      #OtherLetter
      #OtherMarks
      #OtherMaterials
      #OtherModifierLetter
      #OtherPhoneticSymbols
      #OtherVowels
      #OverscoresAndUnderscores
      #OverstruckDiacritics
      #PShipsAndPartsOfShips
      #PaOKarenToneMark
      #PairedArrowsAndHarpoons
      #PairedHarpoons
      #PairedPunctuation
      #PairedTriangleHeadedArrows
      #PakistaniQuranicMarks
      #PalaeotypeTransliterationSymbol
      #PalaeotypeTransliterationSymbols
      #PaliAndSanskritExtensions
      #ParenthesizedHangulLetters
      #ParenthesizedHangulSyllables
      #ParenthesizedIdeographs
      #ParenthesizedKoreanWords
      #ParenthesizedLatinLetters
      #ParenthesizedNumbers
      =Pedals
      =Pentagons
      =PentagramSymbols
      PeopleAndAnimals
      #PersianLetters
      =PersonalCareSymbols
      #PhoneticAndHistoricLetters
      #PhoneticExtensionsForAinu
      #PhoneticSymbol
      #PinyinDiacriticVowelCombinations
      PlantSymbols
      PlayingCardSymbols
      =PlusAndMinusSignOperators
      =PoeticMarks
      =PoetryMarks
      =PointingHandSymbols
      =PointsAndPunctuation
      =PortraitAndRoleSymbols
      =PositioningToneMarks
      #PowerSymbolFromIeee16212004
      #PowerSymbolsFromIso70002012
      #PrecomposedPolytonicGreek
      #PrevailingWindTiles
      #Processes
      #PronunciationVariantsFromKsX10011998
      #ProsodiesProsodics
      #PunctaExtraordinaria
      #Punctuation
      #PunctuationForTibetan
      #PunctuationMark
      #PunctuationMarkOrnaments
      #QDomesticAndFuneraryFurniture
      #QuarterArcConsonantsWrittenDownwards
      #QuarterArcConsonantsWrittenUpwards
      #QuarterCircleVowels
      #QuiltSquareOrnaments
      #QuineCorners
      QuotationMarks
      QuotationMarksAndApostrophe
      #QuranicAnnotationSigns
      #RTempleFurnitureAndSacredEmblems
      #RadixSymbols
      #RaisedSquaredLatinSequences
      RatingSymbols
      RecyclingSymbols
      #ReduplicationMark
      =RegionalIndicatorSymbols
      #Relation
      #RelationalOperators
      #Relations
      =ReligiousAndPoliticalSymbols
      =ReligiousSymbol
      =ReligiousSymbols
      #RepetitionMark
      #RepetitionMarks
      #ReplacementCharacters
      #Rest
      #Rests
      #ReversedPunctuation
      =RibbonArrows
      #RocketOrnaments
      =RoleSymbol
      =RoleSymbols
      =RomanCoinSymbols
      =RomanMilitarySymbol
      RomanNumerals
      =RomanWeightsAndMeasures
      =RomanceSymbols
      =Rosettes
      #RotationModifiers
      #RythmikaRhythmics
      #SCrownsDressStavesEtc
      #Saltires
      #SansSerifArrows
      #SansSerifBoldDigits
      #SansSerifBoldGreekSymbols
      #SansSerifBoldItalicGreekSymbols
      #SansSerifBoldItalicSymbols
      #SansSerifBoldSymbols
      #SansSerifDigits
      #SansSerifItalicSymbols
      #SansSerifSymbols
      #ScanLinesForTerminalGraphics
      #ScriptSymbols
      #SeasonTiles
      #SectionMarks
      #SemiCircleVowels
      #SetMembership
      #SevenStrokeComponents
      #ShadeCharacters
      #ShadedWhiteArrows
      #ShadowedGeometricShapes
      #ShanDigits
      #ShanSymbols
      #ShorthandDoubleMark
      #ShorthandFormatControls
      #ShwePalaungLetters
      #SibeLetters
      #SideliningEmphasisMarks
      #Sign
      #SignForYajurvedic
      #SignageAndOtherSymbols
      #Signs
      #SignsForJaiminiyaSamaVeda
      #SignsForKashmiri
      #SignsForSindhi
      #SignsForYajurvedic
      #SignsUsedInSanskrit
      =SimpleArrows
      =SimpleSigns
      #SindhiImplosives
      #SixPointedStars
      #SixSpokedAsterisks
      #SixStrokeComponents
      #Sixes
      #SixteenStrokeComponents
      #SloanRFormSelector
      =SmallFormVariants
      SmallLetters
      #SmallLettersKhutsuri
      #SogdianLetters
      =SoundSymbols
      #SouthPiceneLetter
      =Space
      =Spaces
      #SpacingAccentMarks
      #SpacingClonesOfDiacritics
      =SpadesOrSwords
      #Special
      #SpecialCharacter
      #SpecialCharacterExtension
      #SpecialCharacterExtensions
      #SpecialCjkIndicators
      #SpecializedPlusSignOperators
      #Specials
      #SpecificSymbolForControlCode
      #SpecificSymbolsForSpace
      SportSymbols
      =SquareSymbols
      =SquaredArrows
      #SquaredHiraganaFromAribStdB24
      #SquaredIdeographs
      #SquaredIdeographsAndKanaFromAribStdB24
      #SquaredKatakana
      #SquaredKatakanaWords
      #SquaredLatinAbbreviation
      #SquaredLatinAbbreviations
      #SquaredLatinLetterSequences
      #SquaredLatinLetterSequencesFromAribStdB62
      #SquaredLatinLetters
      =Squares
      #StaffBrackets
      =Stars
      =StarsAndAsterisks
      =StarsAsterisksAndSnowflakes
      #StatefulTagTerminator
      #Staves
      #Stems
      #StretchedSymbols
      #StretchingOperators
      #SubjoinedConsonant
      #SubjoinedConsonants
      #SubjoinedLetters
      #Subscripts
      #SubscriptsForUpa
      #SubsetAndSupersetRelations
      #SubtendingMarks
      #SummationSignParts
      #SummationsAndIntegrals
      #SuperscriptLetterDiacriticsForGermanDialectology
      #Superscripts
      #SupertendingMark
      #SupplementaryCapitalLetters
      #SupplementarySigns
      #SupplementarySmallLetters
      #SuzhouNumerals
      #Syllable
      #SyllableFinals
      #SyllableInR
      #SyllableIterationMark
      #SyllableReduplicator
      #Syllables
      #SyllablesForBeaverDeneHareDeneAndChipewyanDene
      #SyllablesForBlin
      #SyllablesForCreeAndOjibway
      #SyllablesForMeEn
      #SyllablesForMooseCree
      #SyllablesForSebatbeit
      #SyllablesInA
      #SyllablesInB
      #SyllablesInD
      #SyllablesInE
      #SyllablesInEe
      #SyllablesInF
      #SyllablesInG
      #SyllablesInGb
      #SyllablesInH
      #SyllablesInI
      #SyllablesInJ
      #SyllablesInK
      #SyllablesInKp
      #SyllablesInL
      #SyllablesInM
      #SyllablesInMb
      #SyllablesInN
      #SyllablesInNd
      #SyllablesInNg
      #SyllablesInNgg
      #SyllablesInNj
      #SyllablesInNy
      #SyllablesInO
      #SyllablesInOo
      #SyllablesInP
      #SyllablesInS
      #SyllablesInT
      #SyllablesInU
      #SyllablesInV
      #SyllablesInW
      #SyllablesInWv
      #SyllablesInY
      #Symbol
      #Symbols
      #SymbolsForAntimonyAntimonyOreAndDerivatives
      #SymbolsForAristotelianElements
      #SymbolsForClosedCaptioningFromAribStdB24
      #SymbolsForCopperCopperOreAndDerivatives
      #SymbolsForDraughtsAndCheckers
      #SymbolsForGoldAndSilver
      #SymbolsForImportantSolvents
      #SymbolsForIronIronOreAndDerivatives
      #SymbolsForOtherSubstances
      #SymbolsForSaltVitriolAndNitre
      #SymbolsForSulfurAndMercury
      #SymbolsForTinAndLeadOre
      #SynagmataOrGorgotitesSynagmasOrQuickeners
      #SyriacCrossSymbols
      #SyriacFormatControlCharacter
      #SyriacLetters
      #SyriacMarks
      #SyriacPointsVowels
      #SyriacPunctuationAndSigns
      #TWarfareHuntingButchery
      #Tablature
      #TacksAndTurnstiles
      #TagComponents
      #TagIdentifiers
      #TaiLaingConsonants
      #TaiLaingDigits
      #TaiLaingToneMarks
      #TailedSymbols
      #TamilCalendricalSymbols
      #TamilClericalSymbols
      #TamilNumerics
      #TamilSymbol
      #TangutMark
      #TargetSymbol
      #Tashkil
      #TashkilFromIso88596
      #Tateten
      #TelegraphSymbolsForDays
      #TelegraphSymbolsForHours
      #TelegraphSymbolsForMonths
      #TeluguFractionsAndWeights
      #TenStrokeComponents
      #TenThousands
      #Tens
      #TerminalGraphicCharacters
      #TerminalMark
      #Tetragrams
      #ThamDigits
      #TheIbm32CompatibilityIdeographs
      #ThirteenStrokeComponents
      #Thousands
      #ThreePointedStars
      #ThreeStrokeComponents
      #Threes
      =Time
      =TimeSignatures
      #TodoLetters
      #TolkienianExtensions
      #TonalMarks
      #ToneLetters
      #ToneMarkForTheAtharvaveda
      #ToneMarkForTheRigveda
      #ToneMarks
      #ToneMarksForRohingya
      #ToneMarksForTheSamaveda
      #ToneMarksForTheSatapathabrahmana
      #Tones
      #ToolSymbols
      #TraditionalLetters
      #TrafficSignFromAribStdB24
      TrafficSigns
      #TrafficSignsFromAribStdB24
      #TransliterationHeadLetters
      #TransliterationLetter
      #TransliterationSubjoinedSigns
      #Tremolos
      #TriangleHeadedArrows
      #TriangleHeadedArrowsWithBentTips
      #TriangleHeadedArrowsWithDifferentShaftWeights
      #TriangleHeadedUShapedArrows
      #TriangleSymbols
      Trumps
      =TurnedDigits
      #TwelvePointedStars
      #TwelveStrokeComponents
      #TwoHeadedArrowSymbols
      #TwoPartDependentVowelSigns
      #TwoStrokeComponents
      #Twos
      #UAgricultureCraftsAndProfessions
      #UmbrianLetters
      #UpaModifiers
      #UppercaseConsonants
      #UppercaseLatinAlphabet
      #UppercaseLetters
      #UppercaseSyllables
      #UppercaseVowels
      #UsedForAncientGreek
      #UsedForGermanDialectology
      #UserInterfaceInputStatusSymbols
      #UserInterfaceSymbols
      #VRopeFiberBasketsBagsEtc
      #VariantLetterform
      #VariantLetterforms
      #VariantLetterformsAndSymbols
      #VariantReadingSign
      #VariationSelectors
      #VariousSigns
      =VaseShapes
      #VedicToneMarks
      Vehicles
      #VerticalLineOperator
      #VerticalLineOperators
      #VerticalTiles
      #Vessels
      #VietnameseToneMarks
      #Virama
      #Viramas
      #VocalicModification
      #VoicingMarks
      #Vowel
      #VowelLengthSign
      #VowelLetters
      #VowelRimes
      #VowelSigns
      #Vowels
      #VowelsAndFinals
      =VulgarFractions
      #WVesselsOfStoneAndEarthenware
      WarningSigns
      WeatherAndAstrologicalSymbols
      WeatherLandscapeAndSkySymbols
      WeatherSymbol
      WeatherSymbols
      #WeatherSymbolsFromAribStdB24
      =WhiteAndBlackArrows
      #WhiteArrowShafts
      =WhiteArrowsAndKeyboardSymbols
      =WhiteCircles
      =WhiteCirclesContainingAnotherBlackCircle
      =WhiteDiamondsContainingAnotherBlackDiamond
      #WhiteLozengeContainingAnotherBlackLozenge
      =WhiteOnBlackCircledLatinLetters
      =WhiteOnBlackCircledNumbers
      =WhiteOnBlackSquaredLatinLetters
      =WhiteSquares
      =WhiteSquaresContainingAnotherBlackSquare
      #WideHeadedBarbArrows
      =WordLigature
      =WordLigatureSymbols
      =WordLigatures
      =WordsWithArrows
      #XLoavesAndCakes
      #YWritingsGamesMusic
      #YiRadicals
      #YiddishDigraphs
      #YijingHexagramSymbols
      #YijingMonogramAndDigramSymbols
      #YijingTrigramSymbols
      #ZStrokesSignsDerivedFromHieraticGeometricalFigures
      =Zeroes
      ZodiacalSymbol
      ZodiacalSymbols
    |
#
# and access this configuration in your application as:
#
#     Application.get_env(:string_naming, :key)
#
# You can also configure a 3rd-party app:
#
#     config :logger, level: :info
#

# It is also possible to import configuration files, relative to this
# directory. For example, you can emulate configuration per environment
# by uncommenting the line below and defining dev.exs, test.exs and such.
# Configuration from the imported file will override the ones defined
# here (which is why it is important to import them last).
#
#     import_config "#{Mix.env}.exs"
